### ISSUE TITLE
Rename to macao-social-wallet

### ISSUE THREAD

**Issue by jaromil** [Commonfare-net/macao-social-wallet#81]
At last and after the succesful refactoring made to modularise all libraries and share the same core toolkit for this wallet and the social-wallet-api implementation, we can now think of renaming this "freecoin toolkit application" with another name, to avoid confusion.

I propose "macao-social-wallet", the first implementation of a social wallet done with the freecoin toolkit.

**Comment by aspasia** [comment]
Done
