### ISSUE TITLE
mocking mail server to allow email authentication

### ISSUE THREAD

**Issue by dan-mi-sun** [Commonfare-net/macao-social-wallet#84]
this is issue is connected to #83 

n00b question incoming.

---

When registering a new account it is required to authenticate the email as outlined in:

https://github.com/Commonfare-net/macao-social-wallet/blob/6ad569b516234729809d9910cde4daf8a045f153/test/freecoin/journey/sign_in.clj

due to unfamiliarity with clojure and tooling I'm not sure how to mock out the email. in configuration it is stated:

```
Add an email-conf.edn file and point to it through the conf in project.clj under profiles. It is needed for the system ti be able to send emails when needed (eg. when a user signs up). The file should be of the form: 
{:email-server "" :email-user "" :email-pass "" :email-address ""}
```

Could you give an example of how you set this up for local testing?

Appreciated. 

FYI @kgibb8

**Comment by aspasia** [comment]
We use a simple two factor authentication lib which you can find [here](https://github.com/Commonfare-net/just-auth). If you want to use a real email you need to give the config for the email server. That can be done by creating a email-conf.edn file at the project root containing {:email-server "" :email-user "" :email-pass "" :email-address ""} and fill in the email server details. If you want to mock the email it is also possible, but please explain to me what you are trying to do and then I can assist more. Could be that you dont need the whole wallet but different components from it.

**Comment by dan-mi-sun** [comment]
@aspasia this is a very kind offer. Your time is precious so we need to do more work on scoping our requirements before speaking with you! I'll email you at your dyne address to start a conversation with you however!

**Comment by dan-mi-sun** [comment]
FYI

- so I openend the mongo shell with `mongo`
- `show databases`
- `use freecoin`
- `show collections`
- `db["account-store"].find()`
- This then gives me my user account info including the activation link.

**Comment by aspasia** [comment]
thanks @dan-mi-sun for the info. Personally I am accessing the DB programmatically or by using https://github.com/mongo-express/mongo-express a nice and easy to use UI for it.

**Comment by dan-mi-sun** [comment]
Thanks for the tip. I have found mongo cli ok so far, but will try out the UI :)

FYI - might be nice during testing to be able to load the system with a `testing` flag which automatically activates accounts without needing to click the activation link :)

**Comment by aspasia** [comment]
Noted and on my todo list. I think I might be using the stub email implementation https://github.com/Commonfare-net/just-auth/blob/45a2d65a3fb7fd00eb1b9221d7fe6db8b627e219/src/just_auth/core.clj#L207 whcih uses an atom instead like https://github.com/Commonfare-net/macao-social-wallet/blob/master/test/freecoin/test/handlers/sign_in.clj#L78
