### ISSUE TITLE
example of how to assign value to user accounts

### ISSUE THREAD

**Issue by dan-mi-sun** [Commonfare-net/macao-social-wallet#85]
hi team,

have got everything working but is not immediately clear how to invoke funds at genesis point for accounts. (essentially the system starts with 0 for all new users. How are funds instantiated?)

Is this through the admin console? https://github.com/Commonfare-net/social-wallet-admin-console

If so, could you give an example of the code for how this is done?

If not, could you quickly outline how to add funds to the system.

cc @kgibb8

**Comment by dan-mi-sun** [comment]
For reference here in this demo you start with -124 @aspasia 

https://youtu.be/cAfaBqpozG0?t=11m1s

**Comment by aspasia** [comment]
Hi @dan-mi-sun ,

excellent question!
ATM it is done by adding :admin to an account. Then that account has the right to go minus. We use this for special accounts like the clearing house. You can see an example for it https://github.com/Commonfare-net/macao-social-wallet/blob/6ad569b516234729809d9910cde4daf8a045f153/test/freecoin/test/handlers/transactions.clj#L56. I usually do it manually via the DB for the time being but the idea is exactly what you suggested: it will be done via the admin console. Does it make sense? Thanks for the super useful feedback

**Comment by dan-mi-sun** [comment]
@aspasia Thanks so much!

Have run (from the mongo cli):

```
> db["account-store"].update({_id: "dh@blockades.org"}, {$set:{flags: [":admin"]}})
```

```
> db["account-store"].find({_id: "dh@blockades.org"})
{ "_id" : "dh@blockades.org", "activated" : true, "activation-link" : "http://localhost:8000/activate/dh@blockades.org/oVslsZc8cVFZu5C2iNtOcRFnf9hncxfz", "email" : "dh@blockades.org", "flags" : [  ":admin" ], "name" : "Dan  Hassan", "password" : "pbkdf2+sha512$3ab087dd6bec0620fec71fd4$100000$9a298d7452fd2d00ead8e72269ccd901e9c4be9a6c1d78b4d142a3c3e5ce1f871dcb482e422e8590c5dbaccef255ce0acb71f00ef69a78d47c7f2d156d8778ee" }
```

**Comment by nikolai-b** [comment]
@dan-mi-sun nearly it's

```
> db["account-store"].update({_id: "dh@blockades.org"}, {$set:{flags: ["admin"]}})
```

(no `:` on the admin)

**Comment by dan-mi-sun** [comment]
```> db["account-store"].update({_id: "dh@blockades.org"}, {$set:{flags:["admin"]}})```

Can confirm that this has worked! 

@jaromil , you remember @nikolai-b !?

@aspasia this is another of our good friends working on the mmt project 👍

**Comment by aspasia** [comment]
As I mentioned I m usually using it programmatically so keywords are converted to strings when inserted to the db. Check https://github.com/Commonfare-net/just-auth/blob/45a2d65a3fb7fd00eb1b9221d7fe6db8b627e219/src/just_auth/db/account.clj#L64, https://github.com/Commonfare-net/just-auth/blob/45a2d65a3fb7fd00eb1b9221d7fe6db8b627e219/test/just_auth/test/db/account.clj#L66 and https://github.com/Commonfare-net/just-auth/blob/45a2d65a3fb7fd00eb1b9221d7fe6db8b627e219/src/just_auth/db/account.clj#L45.
Hi @nikolai-b nice you azre getting involved!
