### ISSUE TITLE
vm.box url incorrect in opts/Vagrantfile

### ISSUE THREAD

**Issue by KGibb8** [Commonfare-net/macao-social-wallet#87]
Noticed the virtual box remote url in the Vagrantfile is out of date. Also to get vagrant vm up and running, requires an apt update before installing open-jdk and creating a email-conf.edn for the server to start correctly. I've made a few changes in my own fork, alright to send a PR?

https://github.com/Commonfare-net/macao-social-wallet/compare/master...KGibb8:master

**Comment by aspasia** [comment]
please do! Could you do it against develop and not master? We usually try to keep master to the current production running state. Thanks a lot for your work!!!

**Comment by KGibb8** [comment]
Happy to contribute :+1:  

https://github.com/Commonfare-net/macao-social-wallet/pull/88
